In [101]:
import pandas as pd
import numpy as np

In [102]:
dataset = pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [103]:
x = dataset.iloc[:,:-1].values

In [104]:
y=dataset.iloc[:,3].values

In [105]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [106]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [107]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer


In [108]:
transformer = ColumnTransformer(
    transformers = [
        (
        "das",
        OneHotEncoder(),
        [0]
        )
    ],
    remainder = "passthrough"
)

In [109]:
x= transformer.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, nan],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, nan, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [110]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
x[:,1:3] = imputer.fit_transform(x[:,1:3])
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, nan],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, nan, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [111]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(x,y,test_size=0.3)

In [112]:
x_train

array([[0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 40.0, nan],
       [0.0, 0.0, 1.0, nan, 52000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0]], dtype=object)

In [113]:
y_train

array(['Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No'], dtype=object)

In [114]:
x_test

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [115]:
y_test

array(['No', 'Yes', 'Yes'], dtype=object)

In [116]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [117]:
x_train

array([[-0.40824829, -0.8660254 ,  1.15470054, -1.35250445, -1.09854371],
       [ 2.44948974, -0.8660254 , -0.8660254 ,  0.        ,  0.52787165],
       [-0.40824829,  1.15470054, -0.8660254 ,  0.40575134,         nan],
       [-0.40824829, -0.8660254 ,  1.15470054,         nan, -0.75614048],
       [-0.40824829,  1.15470054, -0.8660254 , -0.94675312, -0.58493886],
       [-0.40824829,  1.15470054, -0.8660254 ,  1.75825579,  1.8974846 ],
       [-0.40824829, -0.8660254 ,  1.15470054,  0.13525045,  0.0142668 ]])

In [118]:
x_test

array([[ 2.44948974, -0.8660254 , -0.8660254 ,  0.94675312,  0.9558757 ],
       [ 2.44948974, -0.8660254 , -0.8660254 ,  1.4877549 ,  1.55508136],
       [ 2.44948974, -0.8660254 , -0.8660254 , -0.27050089, -0.24253563]])